DESARROLLA UNA PLATAFORMA DE  TICKETS PARA REPORTAR DIFERENTES PROBLEMATICAS DE PROBLEMAS DE UN SISTEMA.



DEBE CONTENER LAS SIGUIENTES ENTIDADES.



TICKET (ID TICKET,  TIPO DE TICKET, QUIEN REPORTA, FECHA , ESTATUS, ASESOR QUE ATIENDE, EMPRESA) 

EMPRESA (NOMBRE, DIRECCION, TELEFONO,CORREO, NOMBRE DE CONTACTO.

ASESOR NOMBRE, TELEFONO, CORREO , NUMERO DE TRABAJADOR

CLIENTE NOMBRE, CORREO, EMPRESA



DEBE CONTENER SUS PANTALLAS DE LISTADO, NUEVO, EDITAR. INLCUIR BOTON BORRAR 

LOS BOTONES DEBEN ESTAR PERSONALIZADOS.



DEBE TENER CONTROL DE LOGIN FUNCIONAL, REGISTRAR USUARIOS en html
